### ISSUE TITLE
change dependency from open to opn

### ISSUE THREAD

**Issue by LOK-Soft** [smollweide/contribute-buddy#3]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Issue
There is a dependency to the npm package open which is deprecated and has an critical npm audit warning ( see https://www.npmjs.com/advisories/663 )

## What is the motivation / use case for changing the behavior?
It would be great to change to the package sindresorhus/opn which is referenced as replacement by the open developers.

## Please tell us about your environment
<pre><code>
contribute-buddy version: master
- Node version: 8
- Platform: Mac
</code></pre>

**Comment by smollweide** [comment]
Thank you @LOK-Soft,
no idea why travis build failed in your PR.
It worked with this commit 3de3009
